name: Python package

on:
  push:
    tags: '*'

jobs:

  pypi-publishing:

    runs-on: ubuntu-latest
    steps:
    - name: Install twine and dependencies
      run: |
        python3 -m pip install twine
        python3 -m pip install wheel
    - name: Prepare dist file
      run: python3 setup.py sdist bdist_wheel
    - name: Publish dist on PyPI
      run: python3 -m twine upload --repository testpypi dist/*
