name: Python package

on:
  push:
    tags: '*'

jobs:

  pypi-publishing:

    runs-on: ubuntu-latest
    steps:
    - name: Testing job conditional
      run: python --version
    # - name: Install twine
    #   run: python -m pip install twine
    # - name: Prepare dist file
    #   run: python setup.py sdist
    # - name: Publish dist on PyPI
    #   run: twine upload -r testpypi dist/*
