# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
    tags: '*'
  pull_request:
    branches: [ master ]

jobs:

#   test-postgresql:

#     runs-on: ubuntu-latest

#     services:
#       postgres:
#         image: postgres:10.8
#         env:
#           POSTGRES_USER: postgres
#           POSTGRES_PASSWORD: postgres
#           POSTGRES_DB: github_actions
#         ports:
#           - 5432:5432
#         options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
  
#     strategy:
#       matrix:
#         python-version: [3.5, 3.6, 3.7, 3.8]

#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up Python ${{ matrix.python-version }}
#       uses: actions/setup-python@v1
#       with:
#         python-version: ${{ matrix.python-version }}
#     - name: Install Tox and any other packages
#       run: |
#         python -m pip install --upgrade pip
#         python -m pip install --upgrade pip setuptools wheel
#         pip install tox
#     - name: Run tox
#       run: |
#         export TRYTOND_DATABASE_URI=postgresql://postgres:postgres@localhost:5432/github_actions
#         tox -e py${{ matrix.python-version }}-postgresql

  test-sqlite:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Tox and any other packages
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade pip setuptools wheel
        pip install tox
    - name: Run tox
      run: |
        tox -e py${{ matrix.python-version }}-sqlite

  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: Install Tox and any other packages
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade pip setuptools wheel
        pip install tox
    - name: Run tox
      run: |
        tox -e linters

  pypi-publishing:
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')

    runs-on: ubuntu-latest
    steps:
    - name: Testing job conditional
      run: python --version
    # - name: Install twine
    #   run: python -m pip install twine
    # - name: Prepare dist file
    #   run: python setup.py sdist
    # - name: Publish dist on PyPI
    #   run: twine upload -r testpypi dist/*
